name = "solacabs-backend"
main = "index.js"
compatibility_date = "2025-10-20"
compatibility_flags = ["nodejs_compat"]
account_id = "b7ce0a68968a52be48db93cd0bff48cf"
workers_dev = true

[build]
upload_format = "modules"
