name = "solo-app"
type = "javascript"

account_id = "b7ce0a68968a52be48db93cd0bff48cf"
workers_dev = true
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
[build.upload]
format = "modules"
